# -*- coding: utf-8 -*-
"""Jetson.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9OXNzL4_m-NOSZRMmlh7pKPRhifm4EV
"""

import serial
with serial.Serial('/dev/ttyACM0', 9600, timeout=10) as ser:
    		while True:
        			motor_on = input('Do you want the motor to turn on? ')[0]
        			if motor_on in 'fF':
            			ser.write(bytes('FORWARD\n','utf-8'))
        			if motor_on in 'bB':
            			ser.write(bytes('BACKWARD\n','utf-8'))
			if motor_on in 'rR':
            			ser.write(bytes('RIGHT\n','utf-8'))
        			if motor_on in 'lL':
            			ser.write(bytes('LEFT\n','utf-8'))
			if motor_on in 'sS':
            			ser.write(bytes('STOP\n','utf-8'))